name: hopfield-tracking
channels:
  - defaults
dependencies:
  - _pytorch_select=0.1=cpu_0
  - atomicwrites=1.4.0=py_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - ca-certificates=2021.4.13=haa95532_1
  - certifi=2020.12.5=py38haa95532_0
  - cffi=1.14.5=py38hcd4344a_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - coverage=5.5=py38h2bbff1b_2
  - cycler=0.10.0=py38_0
  - freetype=2.10.4=hd328e21_0
  - icu=58.2=ha925a31_3
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2019.4=245
  - jpeg=9b=hb83a4c4_2
  - kiwisolver=1.3.1=py38hd77b12b_0
  - libmklml=2019.0.5=haa95532_0
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.2.0=hd0e1b90_0
  - lz4-c=1.9.3=h2bbff1b_0
  - matplotlib=3.3.4=py38haa95532_0
  - matplotlib-base=3.3.4=py38h49ac443_0
  - mkl=2019.4=245
  - mkl-service=2.3.0=py38h196d8e1_0
  - mkl_fft=1.3.0=py38h46781fe_0
  - mkl_random=1.1.0=py38hf9181ef_0
  - more-itertools=8.7.0=pyhd3eb1b0_0
  - ninja=1.10.2=h6d14046_1
  - numpy=1.19.2=py38hadc3359_0
  - numpy-base=1.19.2=py38ha3acd2a_0
  - olefile=0.46=py_0
  - openssl=1.1.1k=h2bbff1b_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandas=1.2.4=py38hd77b12b_0
  - pillow=8.2.0=py38h4fa10fc_0
  - pip=21.0.1=py38haa95532_0
  - pluggy=0.13.1=py38haa95532_0
  - py=1.10.0=pyhd3eb1b0_0
  - pycparser=2.20=py_2
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py38ha925a31_4
  - pytest=6.2.3=py38haa95532_2
  - python=3.8.8=hdbf39b2_5
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pytorch=1.6.0=cpu_py38h538a6d7_0
  - pytz=2021.1=pyhd3eb1b0_0
  - qt=5.9.7=vc14h73c81de_0
  - setuptools=52.0.0=py38haa95532_0
  - sip=4.19.13=py38ha925a31_0
  - six=1.15.0=py38haa95532_0
  - sqlite=3.35.4=h2bbff1b_0
  - tk=8.6.10=he774522_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.1=py38h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py38_0
  - xz=5.2.5=h62dcd97_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.5=h04227a9_0
  - pip:
    - torch-testing==0.0.2
prefix: C:\tools\miniconda3\envs\hopfield-tracking
